name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Run Cypress twice 🧪
        uses: cypress-io/github-action@v7.4.0
        with:
          command: npm run demo:twice

      - name: Passes on first try of 2 🧪
        uses: cypress-io/github-action@v7.4.0
        with:
          install: false
          command: npm run demo:until-passes

      # TODO: find a way to verify a failed run
      # or the overall number of runs it takes

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
